### PR TITLE
Add author to package.json.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by sogaani** [comment]
@mrstegeman 
Good morning!

Is this related https://github.com/mozilla-iot/gateway/pull/758/files ?
```sogaani``` is just nickname. So, I feel strange for ```Soga ani``` to divide into last name and first name.
Could I provide ```sogaani``` as author?

**Comment by mrstegeman** [comment]
Yes, that's what it's for. We can use whatever you'd like as your name.

**Comment by mrstegeman** [comment]
I updated the commit with `sogaani`.

**Comment by sogaani** [comment]
thank you!

**Pull request merged**
